feat: add about author and real world entities list to README
Kirill-Stulov/TestGuru pull request #2
Opened 2024-05-06 06:21 UTC by Kirill-Stulov

#comment-starting
- feat: add about author static page
- docs: add list of real-world entities to README

2024-05-06 17:06 UTC, VidgarVii requested changes

2024-05-06 17:06 UTC, VidgarVii commented on README.md
> +  -Some other entities that may make sense:
Этого всего не будет. Но надо куда-то будет записывать результат прохождения теста

2024-05-06 17:06 UTC, VidgarVii commented on public/about/author.html
> +<h4>About author</h4>
файлы из `public` отдаются минуя контроллеры "как есть", т.е. без лэйаута
это означает, что здесь должен быть полноценная `html` страница, которая открывается тегом `<!DOCTYPE html>` и содержит теги `<html>`, `<head>`, `<body>` и т.д.

2024-05-10 13:36 UTC, Kirill-Stulov commented on README.md
> +  -Some other entities that may make sense:
Удалил категории тестов (- Categories), оставил результаты тестов (-Test Results).

2024-05-10 13:37 UTC, Kirill-Stulov commented on public/about/author.html
> +<h4>About author</h4>
Сделал страницы в public полноценными html страницами со стандартным набором тегов.

2024-05-10 13:40 UTC, Kirill-Stulov reviewed
Свежий коммит, после обновлений с учетом комментариев.

2024-05-12 07:27 UTC, VidgarVii requested changes

2024-05-12 07:27 UTC, VidgarVii commented on README.md
> +List of real world entities:
Будут еще Категории (для тестов)

2024-05-12 07:27 UTC, VidgarVii commented on public/about/about_project.html
> +<!DOCTYPE html>
по ТЗ страница должна открываться по пути /about

2024-05-12 07:27 UTC, VidgarVii commented on public/about/about_project.html
> +          Курс проекта: <a href="http://www.thinknetica.com">http://www.thinknetica.com</a>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2024-05-12 07:28 UTC, VidgarVii requested changes

2024-05-12 07:28 UTC, VidgarVii commented on public/1_all_static_pages_here.txt
>  all static pages, which contains public info, are here
этот файл лишний

2024-05-13 10:53 UTC, Kirill-Stulov commented on public/1_all_static_pages_here.txt
>  all static pages, which contains public info, are here
Убрал

2024-05-13 10:53 UTC, Kirill-Stulov commented on public/about/about_project.html
> +          Курс проекта: <a href="http://www.thinknetica.com">http://www.thinknetica.com</a>
Обновил

2024-05-13 10:53 UTC, Kirill-Stulov commented on public/about/about_project.html
> +<!DOCTYPE html>
Перенес

2024-05-13 10:54 UTC, Kirill-Stulov commented on README.md
> +List of real world entities:
Вернул, до этого неверно понял и убрал не то.

2024-05-25 19:25 UTC, VidgarVii requested changes

2024-05-25 19:25 UTC, VidgarVii commented on config/initializers/version.rb
>  APP_VERSION = '0.0.1'
1. Раное еще для патча, когда нет еще минорной версии
2. Не стоит засорять глобальное пространство
версия относится к приложению, так что и константу нужно объявить в его контексте

посмотри к примеру в файл `config/application.rb` в какой модуль обернуто все твое приложение (9-я строка)

```ruby
module TestGuru
  class Application < Rails::Application
    VERSION = '0.1.0'.freeze
  end
end
```

2024-05-25 19:25 UTC, VidgarVii commented on config/application.rb
>      config.active_record.default_timezone = :local
так делать не рекомендуется (`default_timezone = :local`)

стандарт - хранение времени в UTC
это намного удобнее для приложений, в которых используется несколько таймзон (приложение всегда может стать таким)

2024-05-25 19:25 UTC, VidgarVii commented on config/application.rb
>      config.active_record.default_timezone = :local
нет конфига локали по умолчанию

2024-07-10 11:36 UTC, merged