Task 13 rails model fundamentals
Kirill-Stulov/TestGuru pull request #3
Opened 2024-07-10 12:21 UTC by Kirill-Stulov

All commits in this branch on 10 Jul 2024.
1. added a Test, Question, Answer, User, Category models
feat: ran add_tests_title_null_constraint migration
feat: ran add_category_id_to_tests migration
feat: ran add_foreign_key_to_tests_categories migration

2. default values for required attributes in Test and Answer
feat: default value of test level in tests table set to 1
feat: default value for correct attribute in answers table set to false

3. added associations in Test & Question models
feat: Test model. Added associations: belongs_to :category & has_many :questions
feat: Question model. Added associations: belongs_to :test & has_many :answers

2024-07-10 16:25 UTC, VidgarVii requested changes

2024-07-10 16:25 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
ассоциации позже будут в курсе
пока лучше убери их из моделей, чтобы они не отвлекали. Тем более они объявлены не верно.
Нам на данном этапе внешних ключей в таблицах вполне достаточно ближайшие пару уроков нужно будет ручками конструировать запросы, чтобы лучше понять, как ассоциации работают, а потом уже будем использовать ассоциации

2024-07-10 16:25 UTC, VidgarVii commented on db/migrate/20240703092247_add_category_id_to_tests.rb
> +    add_column :tests, :category_id, :integer
не стоит добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом

Пример
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2024-07-10 16:25 UTC, VidgarVii commented on db/migrate/20240616160126_add_tests_title_null_constraint.rb
> +  # def up
такой комментарий не несёт в себе ни какой полезной нагрузки.
Это мусор.
Если код надо удалить, то его надо УДАЛИТЬ, а не комментировать

2024-07-10 16:25 UTC, VidgarVii commented on db/schema.rb
> +  end
для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

2024-07-22 14:23 UTC, Kirill-Stulov commented
Исправил все замечания.

2024-07-23 03:50 UTC, VidgarVii requested changes

2024-07-23 03:50 UTC, VidgarVii commented on db/migrate/20240722053451_create_tests.rb
> +      t.integer :level, default: 1
null: false

2024-07-23 03:50 UTC, VidgarVii commented on db/migrate/20240722053451_create_tests.rb
> +      t.integer :category_id
1. вспоминаем урок по sql. Для полей связей нужны не просто поля, а с указанием на то что это связь, И нужен внешний ключ, для ссылочной целостности.
2. Нет null: false. Не будут тесты без категорий

```
t.references :category, null: false, foreign_key: true
```

2024-07-23 03:50 UTC, VidgarVii commented on db/migrate/20240722053451_create_tests.rb
> +      t.integer :test_author_id # adding column with test author id
1. приставка test_ тут лишняя. Колонка и так относится к таблице тесты
2. Комментарий лишний. Название колонки должно говорить само за себя
3. Нет внешнего ключа

2024-07-23 03:50 UTC, VidgarVii commented on db/migrate/20240722125705_create_questions.rb
> +      t.text :body, limit: 600, null: false
для чего нужен поле title и для чего body? Мне кажется одного текстового поля хватит для хранения текста вопроса.

2024-07-23 03:50 UTC, VidgarVii commented on db/migrate/20240722132535_create_answers.rb
> +      t.boolean :correct, default: false
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2024-12-25 10:22 UTC, merged